import type { Metadata } from "next";
import {
  // Geist,
  // Geist_Mono,
  Noto_Sans_JP,
  // IBM_Plex_Sans_JP,
} from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const notoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "700"],
  preload: false,
  variable: "--font-noto-sans-jp",
  display: "swap",
  fallback: ["Hiragino Sans", "Hiragino Kaku Gothic ProN", "sans-serif"],
});

// const ibm_Plex_Sans_JP = IBM_Plex_Sans_JP({
//   subsets: ["latin"],
//   weight: ["400", "700"],
//   preload: false,
//   variable: "--font-ibm-plex-sans-jp",
//   display: "swap",
//   fallback: ["Hiragino Sans", "Hiragino Kaku Gothic ProN", "sans-serif"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${notoSansJp.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${notoSansJp.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
